spring:
  application:
    name: microservice-consumer-movie-ribbon
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zrd123:zrd123@localhost:8761/eureka
  instance:
    prefer-ip-address: true