spring:
  application:
    name: microservice-gateway-zuul

eureka:
  client:
    service-url:
       defaultZone: http://zrd123:zrd123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8040
#通过这种方式实现对用户微服务的负载均衡
zuul:
  routes:
    users:
      path: /myusers/**
      serviceId: microservice-provider-user
ribbon:
  eureka:
    enabled: false


microservice-provider-user:   #这里指定的是 serviceid
  ribbon:
    listOfServers: http://localhost:9008,http://localhost:9009



