spring:
  application:
    name: microservice-consumer-movie-fegin
server:
  port: 9898
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zrd123:zrd123@localhost:8761/eureka
  instance:
    prefer-ip-address: true