server:
  port: 8761

eureka:
  datacenter: myzrdcloud
  environment: myzrdproduct
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://zrd123:zrd123@localhost:8761/eureka
#  server:
#    enable-self-preservation: false
security:
  basic:
    enabled: true
  user:
    name: zrd123
    password: zrd123


