spring:
  application:
    name: microservice-consumer-movie
server:
  port: 7911
user:
  userServicePath: http://localhost:7901/simple/
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zrd123:zrd123@localhost:8761/eureka
  instance:
    prefer-ip-address: true